#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoanThien
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyShipper")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDonHang(DonHang instance);
    partial void UpdateDonHang(DonHang instance);
    partial void DeleteDonHang(DonHang instance);
    partial void InsertShipper(Shipper instance);
    partial void UpdateShipper(Shipper instance);
    partial void DeleteShipper(Shipper instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void Insertmarker(marker instance);
    partial void Updatemarker(marker instance);
    partial void Deletemarker(marker instance);
    partial void InsertQuanLy(QuanLy instance);
    partial void UpdateQuanLy(QuanLy instance);
    partial void DeleteQuanLy(QuanLy instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::HoanThien.Properties.Settings.Default.QuanLyShipperConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DonHang> DonHangs
		{
			get
			{
				return this.GetTable<DonHang>();
			}
		}
		
		public System.Data.Linq.Table<Shipper> Shippers
		{
			get
			{
				return this.GetTable<Shipper>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<marker> markers
		{
			get
			{
				return this.GetTable<marker>();
			}
		}
		
		public System.Data.Linq.Table<QuanLy> QuanLies
		{
			get
			{
				return this.GetTable<QuanLy>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonHang")]
	public partial class DonHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDon;
		
		private string _TenHang;
		
		private string _TenNguoiNhan;
		
		private string _SDTNN;
		
		private string _Diachinhanhang;
		
		private string _DiaChigiaohang;
		
		private string _Tinhtrangdonhang;
		
		private string _MaSP;
		
		private string _MaKH;
		
		private string _MaQL;
		
		private string _Loai_Hang;
		
		private System.DateTime _Thoidiemdathang;
		
		private System.DateTime _Thoidiemgiaohang;
		
		private EntityRef<Shipper> _Shipper;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<QuanLy> _QuanLy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonChanging(string value);
    partial void OnMaDonChanged();
    partial void OnTenHangChanging(string value);
    partial void OnTenHangChanged();
    partial void OnTenNguoiNhanChanging(string value);
    partial void OnTenNguoiNhanChanged();
    partial void OnSDTNNChanging(string value);
    partial void OnSDTNNChanged();
    partial void OnDiachinhanhangChanging(string value);
    partial void OnDiachinhanhangChanged();
    partial void OnDiaChigiaohangChanging(string value);
    partial void OnDiaChigiaohangChanged();
    partial void OnTinhtrangdonhangChanging(string value);
    partial void OnTinhtrangdonhangChanged();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnMaQLChanging(string value);
    partial void OnMaQLChanged();
    partial void OnLoai_HangChanging(string value);
    partial void OnLoai_HangChanged();
    partial void OnThoidiemdathangChanging(System.DateTime value);
    partial void OnThoidiemdathangChanged();
    partial void OnThoidiemgiaohangChanging(System.DateTime value);
    partial void OnThoidiemgiaohangChanged();
    #endregion
		
		public DonHang()
		{
			this._Shipper = default(EntityRef<Shipper>);
			this._KhachHang = default(EntityRef<KhachHang>);
			this._QuanLy = default(EntityRef<QuanLy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDon", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDon
		{
			get
			{
				return this._MaDon;
			}
			set
			{
				if ((this._MaDon != value))
				{
					this.OnMaDonChanging(value);
					this.SendPropertyChanging();
					this._MaDon = value;
					this.SendPropertyChanged("MaDon");
					this.OnMaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHang", DbType="NVarChar(60)")]
		public string TenHang
		{
			get
			{
				return this._TenHang;
			}
			set
			{
				if ((this._TenHang != value))
				{
					this.OnTenHangChanging(value);
					this.SendPropertyChanging();
					this._TenHang = value;
					this.SendPropertyChanged("TenHang");
					this.OnTenHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiNhan", DbType="NVarChar(50)")]
		public string TenNguoiNhan
		{
			get
			{
				return this._TenNguoiNhan;
			}
			set
			{
				if ((this._TenNguoiNhan != value))
				{
					this.OnTenNguoiNhanChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiNhan = value;
					this.SendPropertyChanged("TenNguoiNhan");
					this.OnTenNguoiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTNN", DbType="NVarChar(13)")]
		public string SDTNN
		{
			get
			{
				return this._SDTNN;
			}
			set
			{
				if ((this._SDTNN != value))
				{
					this.OnSDTNNChanging(value);
					this.SendPropertyChanging();
					this._SDTNN = value;
					this.SendPropertyChanged("SDTNN");
					this.OnSDTNNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachinhanhang", DbType="NVarChar(50)")]
		public string Diachinhanhang
		{
			get
			{
				return this._Diachinhanhang;
			}
			set
			{
				if ((this._Diachinhanhang != value))
				{
					this.OnDiachinhanhangChanging(value);
					this.SendPropertyChanging();
					this._Diachinhanhang = value;
					this.SendPropertyChanged("Diachinhanhang");
					this.OnDiachinhanhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChigiaohang", DbType="NVarChar(50)")]
		public string DiaChigiaohang
		{
			get
			{
				return this._DiaChigiaohang;
			}
			set
			{
				if ((this._DiaChigiaohang != value))
				{
					this.OnDiaChigiaohangChanging(value);
					this.SendPropertyChanging();
					this._DiaChigiaohang = value;
					this.SendPropertyChanged("DiaChigiaohang");
					this.OnDiaChigiaohangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtrangdonhang", DbType="NVarChar(40)")]
		public string Tinhtrangdonhang
		{
			get
			{
				return this._Tinhtrangdonhang;
			}
			set
			{
				if ((this._Tinhtrangdonhang != value))
				{
					this.OnTinhtrangdonhangChanging(value);
					this.SendPropertyChanging();
					this._Tinhtrangdonhang = value;
					this.SendPropertyChanged("Tinhtrangdonhang");
					this.OnTinhtrangdonhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="NVarChar(50)")]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					if (this._Shipper.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NVarChar(50)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQL", DbType="NVarChar(50)")]
		public string MaQL
		{
			get
			{
				return this._MaQL;
			}
			set
			{
				if ((this._MaQL != value))
				{
					if (this._QuanLy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQLChanging(value);
					this.SendPropertyChanging();
					this._MaQL = value;
					this.SendPropertyChanged("MaQL");
					this.OnMaQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai_Hang", DbType="NVarChar(50)")]
		public string Loai_Hang
		{
			get
			{
				return this._Loai_Hang;
			}
			set
			{
				if ((this._Loai_Hang != value))
				{
					this.OnLoai_HangChanging(value);
					this.SendPropertyChanging();
					this._Loai_Hang = value;
					this.SendPropertyChanged("Loai_Hang");
					this.OnLoai_HangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoidiemdathang", DbType="Date NOT NULL")]
		public System.DateTime Thoidiemdathang
		{
			get
			{
				return this._Thoidiemdathang;
			}
			set
			{
				if ((this._Thoidiemdathang != value))
				{
					this.OnThoidiemdathangChanging(value);
					this.SendPropertyChanging();
					this._Thoidiemdathang = value;
					this.SendPropertyChanged("Thoidiemdathang");
					this.OnThoidiemdathangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoidiemgiaohang", DbType="Date NOT NULL")]
		public System.DateTime Thoidiemgiaohang
		{
			get
			{
				return this._Thoidiemgiaohang;
			}
			set
			{
				if ((this._Thoidiemgiaohang != value))
				{
					this.OnThoidiemgiaohangChanging(value);
					this.SendPropertyChanging();
					this._Thoidiemgiaohang = value;
					this.SendPropertyChanged("Thoidiemgiaohang");
					this.OnThoidiemgiaohangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Shipper_DonHang", Storage="_Shipper", ThisKey="MaSP", OtherKey="MaSP", IsForeignKey=true)]
		public Shipper Shipper
		{
			get
			{
				return this._Shipper.Entity;
			}
			set
			{
				Shipper previousValue = this._Shipper.Entity;
				if (((previousValue != value) 
							|| (this._Shipper.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Shipper.Entity = null;
						previousValue.DonHangs.Remove(this);
					}
					this._Shipper.Entity = value;
					if ((value != null))
					{
						value.DonHangs.Add(this);
						this._MaSP = value.MaSP;
					}
					else
					{
						this._MaSP = default(string);
					}
					this.SendPropertyChanged("Shipper");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonHang", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DonHangs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DonHangs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanLy_DonHang", Storage="_QuanLy", ThisKey="MaQL", OtherKey="MaQL", IsForeignKey=true)]
		public QuanLy QuanLy
		{
			get
			{
				return this._QuanLy.Entity;
			}
			set
			{
				QuanLy previousValue = this._QuanLy.Entity;
				if (((previousValue != value) 
							|| (this._QuanLy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuanLy.Entity = null;
						previousValue.DonHangs.Remove(this);
					}
					this._QuanLy.Entity = value;
					if ((value != null))
					{
						value.DonHangs.Add(this);
						this._MaQL = value.MaQL;
					}
					else
					{
						this._MaQL = default(string);
					}
					this.SendPropertyChanged("QuanLy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shipper")]
	public partial class Shipper : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSP;
		
		private string _emailSP;
		
		private string _tenShipper;
		
		private string _cccd;
		
		private string _sdtShipper;
		
		private string _TaiKhoanSP;
		
		private string _MatKhauSP;
		
		private string _DiaChiSP;
		
		private EntitySet<DonHang> _DonHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnemailSPChanging(string value);
    partial void OnemailSPChanged();
    partial void OntenShipperChanging(string value);
    partial void OntenShipperChanged();
    partial void OncccdChanging(string value);
    partial void OncccdChanged();
    partial void OnsdtShipperChanging(string value);
    partial void OnsdtShipperChanged();
    partial void OnTaiKhoanSPChanging(string value);
    partial void OnTaiKhoanSPChanged();
    partial void OnMatKhauSPChanging(string value);
    partial void OnMatKhauSPChanged();
    partial void OnDiaChiSPChanging(string value);
    partial void OnDiaChiSPChanged();
    #endregion
		
		public Shipper()
		{
			this._DonHangs = new EntitySet<DonHang>(new Action<DonHang>(this.attach_DonHangs), new Action<DonHang>(this.detach_DonHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailSP", DbType="NVarChar(50)")]
		public string emailSP
		{
			get
			{
				return this._emailSP;
			}
			set
			{
				if ((this._emailSP != value))
				{
					this.OnemailSPChanging(value);
					this.SendPropertyChanging();
					this._emailSP = value;
					this.SendPropertyChanged("emailSP");
					this.OnemailSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenShipper", DbType="NVarChar(50)")]
		public string tenShipper
		{
			get
			{
				return this._tenShipper;
			}
			set
			{
				if ((this._tenShipper != value))
				{
					this.OntenShipperChanging(value);
					this.SendPropertyChanging();
					this._tenShipper = value;
					this.SendPropertyChanged("tenShipper");
					this.OntenShipperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cccd", DbType="NVarChar(12)")]
		public string cccd
		{
			get
			{
				return this._cccd;
			}
			set
			{
				if ((this._cccd != value))
				{
					this.OncccdChanging(value);
					this.SendPropertyChanging();
					this._cccd = value;
					this.SendPropertyChanged("cccd");
					this.OncccdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtShipper", DbType="NVarChar(13)")]
		public string sdtShipper
		{
			get
			{
				return this._sdtShipper;
			}
			set
			{
				if ((this._sdtShipper != value))
				{
					this.OnsdtShipperChanging(value);
					this.SendPropertyChanging();
					this._sdtShipper = value;
					this.SendPropertyChanged("sdtShipper");
					this.OnsdtShipperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoanSP", DbType="NVarChar(30)")]
		public string TaiKhoanSP
		{
			get
			{
				return this._TaiKhoanSP;
			}
			set
			{
				if ((this._TaiKhoanSP != value))
				{
					this.OnTaiKhoanSPChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoanSP = value;
					this.SendPropertyChanged("TaiKhoanSP");
					this.OnTaiKhoanSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauSP", DbType="NVarChar(30)")]
		public string MatKhauSP
		{
			get
			{
				return this._MatKhauSP;
			}
			set
			{
				if ((this._MatKhauSP != value))
				{
					this.OnMatKhauSPChanging(value);
					this.SendPropertyChanging();
					this._MatKhauSP = value;
					this.SendPropertyChanged("MatKhauSP");
					this.OnMatKhauSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiSP", DbType="NVarChar(30)")]
		public string DiaChiSP
		{
			get
			{
				return this._DiaChiSP;
			}
			set
			{
				if ((this._DiaChiSP != value))
				{
					this.OnDiaChiSPChanging(value);
					this.SendPropertyChanging();
					this._DiaChiSP = value;
					this.SendPropertyChanged("DiaChiSP");
					this.OnDiaChiSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Shipper_DonHang", Storage="_DonHangs", ThisKey="MaSP", OtherKey="MaSP")]
		public EntitySet<DonHang> DonHangs
		{
			get
			{
				return this._DonHangs;
			}
			set
			{
				this._DonHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonHangs(DonHang entity)
		{
			this.SendPropertyChanging();
			entity.Shipper = this;
		}
		
		private void detach_DonHangs(DonHang entity)
		{
			this.SendPropertyChanging();
			entity.Shipper = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _emailKH;
		
		private string _SDTKH;
		
		private string _TaiKhoanKH;
		
		private string _MatKhauKH;
		
		private string _DiaChiKH;
		
		private EntitySet<DonHang> _DonHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnemailKHChanging(string value);
    partial void OnemailKHChanged();
    partial void OnSDTKHChanging(string value);
    partial void OnSDTKHChanged();
    partial void OnTaiKhoanKHChanging(string value);
    partial void OnTaiKhoanKHChanged();
    partial void OnMatKhauKHChanging(string value);
    partial void OnMatKhauKHChanged();
    partial void OnDiaChiKHChanging(string value);
    partial void OnDiaChiKHChanged();
    #endregion
		
		public KhachHang()
		{
			this._DonHangs = new EntitySet<DonHang>(new Action<DonHang>(this.attach_DonHangs), new Action<DonHang>(this.detach_DonHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailKH", DbType="NVarChar(50)")]
		public string emailKH
		{
			get
			{
				return this._emailKH;
			}
			set
			{
				if ((this._emailKH != value))
				{
					this.OnemailKHChanging(value);
					this.SendPropertyChanging();
					this._emailKH = value;
					this.SendPropertyChanged("emailKH");
					this.OnemailKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTKH", DbType="NVarChar(13)")]
		public string SDTKH
		{
			get
			{
				return this._SDTKH;
			}
			set
			{
				if ((this._SDTKH != value))
				{
					this.OnSDTKHChanging(value);
					this.SendPropertyChanging();
					this._SDTKH = value;
					this.SendPropertyChanged("SDTKH");
					this.OnSDTKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoanKH", DbType="NVarChar(50)")]
		public string TaiKhoanKH
		{
			get
			{
				return this._TaiKhoanKH;
			}
			set
			{
				if ((this._TaiKhoanKH != value))
				{
					this.OnTaiKhoanKHChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoanKH = value;
					this.SendPropertyChanged("TaiKhoanKH");
					this.OnTaiKhoanKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauKH", DbType="NVarChar(50)")]
		public string MatKhauKH
		{
			get
			{
				return this._MatKhauKH;
			}
			set
			{
				if ((this._MatKhauKH != value))
				{
					this.OnMatKhauKHChanging(value);
					this.SendPropertyChanging();
					this._MatKhauKH = value;
					this.SendPropertyChanged("MatKhauKH");
					this.OnMatKhauKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiKH", DbType="NVarChar(50)")]
		public string DiaChiKH
		{
			get
			{
				return this._DiaChiKH;
			}
			set
			{
				if ((this._DiaChiKH != value))
				{
					this.OnDiaChiKHChanging(value);
					this.SendPropertyChanging();
					this._DiaChiKH = value;
					this.SendPropertyChanged("DiaChiKH");
					this.OnDiaChiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonHang", Storage="_DonHangs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<DonHang> DonHangs
		{
			get
			{
				return this._DonHangs;
			}
			set
			{
				this._DonHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonHangs(DonHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DonHangs(DonHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.markers")]
	public partial class marker : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<double> _latitude;
		
		private System.Nullable<double> _longitude;
		
		private string _label;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnlatitudeChanging(System.Nullable<double> value);
    partial void OnlatitudeChanged();
    partial void OnlongitudeChanging(System.Nullable<double> value);
    partial void OnlongitudeChanged();
    partial void OnlabelChanging(string value);
    partial void OnlabelChanged();
    #endregion
		
		public marker()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="Float")]
		public System.Nullable<double> latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this.OnlatitudeChanging(value);
					this.SendPropertyChanging();
					this._latitude = value;
					this.SendPropertyChanged("latitude");
					this.OnlatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Float")]
		public System.Nullable<double> longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_label", DbType="NVarChar(255)")]
		public string label
		{
			get
			{
				return this._label;
			}
			set
			{
				if ((this._label != value))
				{
					this.OnlabelChanging(value);
					this.SendPropertyChanging();
					this._label = value;
					this.SendPropertyChanged("label");
					this.OnlabelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanLy")]
	public partial class QuanLy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaQL;
		
		private string _TenQL;
		
		private string _TaiKhoanQL;
		
		private string _MatKhauQL;
		
		private EntitySet<DonHang> _DonHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQLChanging(string value);
    partial void OnMaQLChanged();
    partial void OnTenQLChanging(string value);
    partial void OnTenQLChanged();
    partial void OnTaiKhoanQLChanging(string value);
    partial void OnTaiKhoanQLChanged();
    partial void OnMatKhauQLChanging(string value);
    partial void OnMatKhauQLChanged();
    #endregion
		
		public QuanLy()
		{
			this._DonHangs = new EntitySet<DonHang>(new Action<DonHang>(this.attach_DonHangs), new Action<DonHang>(this.detach_DonHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQL", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaQL
		{
			get
			{
				return this._MaQL;
			}
			set
			{
				if ((this._MaQL != value))
				{
					this.OnMaQLChanging(value);
					this.SendPropertyChanging();
					this._MaQL = value;
					this.SendPropertyChanged("MaQL");
					this.OnMaQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQL", DbType="NVarChar(50)")]
		public string TenQL
		{
			get
			{
				return this._TenQL;
			}
			set
			{
				if ((this._TenQL != value))
				{
					this.OnTenQLChanging(value);
					this.SendPropertyChanging();
					this._TenQL = value;
					this.SendPropertyChanged("TenQL");
					this.OnTenQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoanQL", DbType="NVarChar(50)")]
		public string TaiKhoanQL
		{
			get
			{
				return this._TaiKhoanQL;
			}
			set
			{
				if ((this._TaiKhoanQL != value))
				{
					this.OnTaiKhoanQLChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoanQL = value;
					this.SendPropertyChanged("TaiKhoanQL");
					this.OnTaiKhoanQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauQL", DbType="NVarChar(50)")]
		public string MatKhauQL
		{
			get
			{
				return this._MatKhauQL;
			}
			set
			{
				if ((this._MatKhauQL != value))
				{
					this.OnMatKhauQLChanging(value);
					this.SendPropertyChanging();
					this._MatKhauQL = value;
					this.SendPropertyChanged("MatKhauQL");
					this.OnMatKhauQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanLy_DonHang", Storage="_DonHangs", ThisKey="MaQL", OtherKey="MaQL")]
		public EntitySet<DonHang> DonHangs
		{
			get
			{
				return this._DonHangs;
			}
			set
			{
				this._DonHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonHangs(DonHang entity)
		{
			this.SendPropertyChanging();
			entity.QuanLy = this;
		}
		
		private void detach_DonHangs(DonHang entity)
		{
			this.SendPropertyChanging();
			entity.QuanLy = null;
		}
	}
}
#pragma warning restore 1591
